language: php
php:
    - '7.2'
    - nightly
services:
    - mysql
    - redis
    - memcached
before_script:
    - pecl install ast
    - composer install
    - git clone -b develop https://github.com/Orange-Management/Build.git
    - chmod -R 755 Build/Hooks
    - cd ..
    - git clone -b develop https://github.com/Orange-Management/phpOMS.git
    - cd Modules
    - pecl install redis
    - echo "extension=redis.so" | tee /.phpenv/versions/$(phpenv version-name)/etc/conf.d/redis.ini
    - phpenmod redis
    - pecl install memcached
    - echo "extension=memcached.so" | tee /.phpenv/versions/$(phpenv version-name)/etc/conf.d/memcached.ini
    - phpenmod memcached
script:
    - vendor/bin/phpunit --version && vendor/bin/phpunit --configuration tests/phpunit_no_coverage.xml
    - ./Build/Hooks/travis.sh
notifications:
    email: false